name = "sarour-store-final-v10-cloudflar"
main = "src/worker.js"
compatibility_date = "2026-07-28"

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "sarour_stor_premium"
database_id = "efd761a1-66e1-49a6-b08f-8c3b1937d889"

[vars]
PAYMENT_MODE = "sandbox"

